In [2]:
#1.3.1 задание

b = np.zeros((8,8), dtype=int)
b[1::2, ::2] = 1
b[::2, 1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
#1.3.2 задание

import numpy as np

b = np.arange(5)
a = np.zeros((5, 5))
a = a + b


print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [4]:
#1.3.3 задание

import numpy as np
z = np.random.uniform(low=0, high=1, size=(3, 3, 3))
print(z)

[[[0.67656345 0.2807275  0.63894042]
  [0.09975625 0.04059246 0.54410993]
  [0.94959438 0.9062502  0.05529699]]

 [[0.97550303 0.4837908  0.37359018]
  [0.38878568 0.41648789 0.14909284]
  [0.76023378 0.60214399 0.90294675]]

 [[0.61870172 0.36850304 0.70993023]
  [0.73235955 0.70335628 0.48174979]
  [0.82161574 0.07893209 0.33972115]]]


In [6]:
#1.3.4 задание

import numpy as np
z = np.full((5, 5), 1)
z[1:-1, 1:-1] = 0
print(z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [8]:
#1.3.5 задание

import numpy as np

z = np.random.uniform(low=0, high=10, size=10)
print(z)
z = np.sort(z)[::-1]
print(z)

[9.09916526 0.4518731  0.04408952 5.6683113  5.76372126 2.98101796
 2.48146966 4.30346861 2.06818437 5.74181479]
[9.09916526 5.76372126 5.74181479 5.6683113  4.30346861 2.98101796
 2.48146966 2.06818437 0.4518731  0.04408952]


In [9]:
#1.3.6 задание

import numpy as np

z = np.random.uniform(low=0, high=5, size=(5, 5))
print("form: ", z.shape)
print("size: ", z.size)
print("ndim: ", z.ndim)

form:  (5, 5)
size:  25
ndim:  2


In [41]:
#2.3.1 задание

import pandas as pd

a = pd.Series([2, 4, 6, 8])
b = pd.Series([1, 3, 5, 7])
ans = sum((a - b)**2)**0.5
print(ans)

2.0


In [42]:
#2.3.2 задание

import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/elevators.csv'
dataframe = pd.read_csv(url, on_bad_lines='skip')

dataframe.head(5)

1   2     3     4    5   6   7      8    9      10      11      12  \
0 -178  40 -0.11  0.13  1.1  -9 -12 -0.011  0.0 -0.0007 -0.0007 -0.0007   
1 -122   9  0.27  0.05  0.0 -10  -2 -0.005  0.4 -0.0007 -0.0007 -0.0007   
2  196 -10 -0.44  0.10  0.6 -10  -7  0.003  0.2 -0.0006 -0.0006 -0.0006   
3  507  -6  0.14  0.10 -0.2 -10   2  0.001 -0.7 -0.0007 -0.0006 -0.0006   
4 -189 -67 -0.60 -0.08  0.5 -14  17 -0.017 -0.7 -0.0013 -0.0013 -0.0013   

       13      14   15   16   17      18      y  
0 -0.0007  0.0000  0.0  0.0  0.0 -0.0007  0.018  
1 -0.0007  0.0000  0.0  0.0  0.0 -0.0007  0.017  
2 -0.0006  0.0000  0.0  0.0  0.0 -0.0006  0.021  
3 -0.0006 -0.0001  0.0  0.0  0.0 -0.0006  0.024  
4 -0.0013  0.0000  0.0  0.0  0.0 -0.0013  0.018

In [44]:
#2.3.3 задание

dataframe.tail(5)


1   2     3     4    5   6   7      8    9      10      11      12  \
16594 -162 -24  0.27  0.03  0.8 -10   2 -0.009 -0.1 -0.0022 -0.0021 -0.0021   
16595   12 -31  0.20 -0.08 -0.3 -13  12 -0.003  1.3 -0.0008 -0.0008 -0.0008   
16596 -243 -23  0.08 -0.11 -0.7  -7  13  0.007 -0.2 -0.0005 -0.0005 -0.0005   
16597 -226  15 -0.17 -0.01 -0.5  -7   6  0.001 -0.8 -0.0005 -0.0005 -0.0005   
16598 -193  -2 -0.36  0.04 -0.8 -16 -11 -0.026  3.6 -0.0014 -0.0014 -0.0014   

           13      14   15      16   17      18      y  
16594 -0.0017 -0.0002  0.0 -0.0004  0.0 -0.0017  0.052  
16595 -0.0008  0.0000  0.0  0.0000  0.0 -0.0008  0.017  
16596 -0.0005  0.0000  0.0  0.0000  0.0 -0.0005  0.033  
16597 -0.0005  0.0000  0.0  0.0000  0.0 -0.0005  0.016  
16598 -0.0014  0.0000  0.0  0.0000  0.0 -0.0014  0.018

In [27]:
#2.3.3 задание

print(dataframe.shape)


(16599, 19)


In [28]:
#2.3.3 задание

dataframe.describe()

1             2             3             4             5  \
count  16599.000000  16599.000000  16599.000000  16599.000000  16599.000000   
mean     -11.795771    -12.798783     -0.010076      0.054490      0.046894   
std      277.593632     25.439814      0.310457      0.115866      0.951701   
min     -993.000000    -99.000000     -1.370000     -0.450000     -3.000000   
25%     -200.000000    -29.000000     -0.230000     -0.030000     -0.600000   
50%      -31.000000    -13.000000      0.000000      0.050000      0.100000   
75%      177.000000      3.000000      0.220000      0.130000      0.700000   
max      973.000000     94.000000      1.090000      0.690000      2.900000   

                  6             7             8             9            10  \
count  16599.000000  16599.000000  16599.000000  16599.000000  16599.000000   
mean     -10.789626     -0.569793     -0.001049     -0.033978     -0.000750   
std        4.102681     10.568555      0.012587      0.949416      0.000402   
min      -23.000000    -56.000000     -0.084000     -8.300000     -0.003500   
25%      -13.000000     -8.000000     -0.009000     -0.200000     -0.000900   
50%      -10.000000      0.000000     -0.001000     -0.100000     -0.000700   
75%       -7.000000      6.000000      0.007000      0.100000     -0.000500   
max       -3.000000     45.000000      0.056000      8.500000      0.000000   

                 11            12            13            14            15  \
count  16599.000000  16599.000000  16599.000000  16599.000000  1.659900e+04   
mean      -0.000754     -0.000754     -0.000757     -0.000009  1.807338e-08   
std        0.000407      0.000408      0.000410      0.000086  1.735536e-06   
min       -0.003500     -0.003500     -0.003400     -0.000700  0.000000e+00   
25%       -0.000900     -0.000900     -0.001000      0.000000  0.000000e+00   
50%       -0.000700     -0.000700     -0.000700      0.000000  0.000000e+00   
75%       -0.000500     -0.000500     -0.000500      0.000000  0.000000e+00   
max        0.000000      0.000000      0.000000      0.000700  2.000000e-04   

                 16            17            18             y  
count  16599.000000  1.659900e+04  16599.000000  16599.000000  
mean      -0.000003  3.012230e-08     -0.000757      0.021625  
std        0.000058  2.328397e-06      0.000410      0.006717  
min       -0.000600  0.000000e+00     -0.003400      0.012000  
25%        0.000000  0.000000e+00     -0.001000      0.018000  
50%        0.000000  0.000000e+00     -0.000700      0.020000  
75%        0.000000  0.000000e+00     -0.000500      0.023000  
max        0.000500  2.000000e-04      0.000000      0.078000

In [29]:
#2.3.3 задание

dataframe.iloc[5:10]

1   2     3     4    5   6   7      8    9      10      11      12  \
5  -22  22  0.14  0.04 -0.7  -9   4  0.011 -0.9 -0.0007 -0.0007 -0.0007   
6 -119  -5 -0.13  0.06  1.0  -8  -5 -0.004  0.0 -0.0006 -0.0006 -0.0006   
7 -184 -10  0.37 -0.03 -0.3 -15  15  0.014 -0.5 -0.0008 -0.0007 -0.0007   
8  -25 -17 -0.16  0.10  0.4 -19   6  0.011  0.2 -0.0011 -0.0011 -0.0011   
9 -178  -4 -0.22  0.00  0.4  -6   1 -0.006  0.0 -0.0005 -0.0005 -0.0005   

       13      14   15   16   17      18      y  
5 -0.0007  0.0000  0.0  0.0  0.0 -0.0007  0.053  
6 -0.0006  0.0000  0.0  0.0  0.0 -0.0006  0.017  
7 -0.0007 -0.0003  0.0  0.0  0.0 -0.0007  0.018  
8 -0.0011  0.0000  0.0  0.0  0.0 -0.0011  0.025  
9 -0.0005  0.0000  0.0  0.0  0.0 -0.0005  0.017

In [30]:
#2.3.3 задание

dataframe[dataframe['y'] == 0.018].head(5)

1   2     3     4    5   6   7      8    9      10      11      12  \
0  -178  40 -0.11  0.13  1.1  -9 -12 -0.011  0.0 -0.0007 -0.0007 -0.0007   
4  -189 -67 -0.60 -0.08  0.5 -14  17 -0.017 -0.7 -0.0013 -0.0013 -0.0013   
7  -184 -10  0.37 -0.03 -0.3 -15  15  0.014 -0.5 -0.0008 -0.0007 -0.0007   
10 -373  34  0.06  0.12 -0.1  -9 -11  0.004  0.0 -0.0005 -0.0005 -0.0005   
11  123 -11  0.10 -0.02 -0.7  -7   2  0.004 -0.1 -0.0003 -0.0003 -0.0003   

        13      14   15   16   17      18      y  
0  -0.0007  0.0000  0.0  0.0  0.0 -0.0007  0.018  
4  -0.0013  0.0000  0.0  0.0  0.0 -0.0013  0.018  
7  -0.0007 -0.0003  0.0  0.0  0.0 -0.0007  0.018  
10 -0.0005  0.0000  0.0  0.0  0.0 -0.0005  0.018  
11 -0.0003  0.0000  0.0  0.0  0.0 -0.0003  0.018

In [39]:
#3.3.2 задание

new_url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
data = pd.read_csv(new_url, on_bad_lines='skip')
data.head(10)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa
5              5.4             3.9              1.7             0.4  setosa
6              4.6             3.4              1.4             0.3  setosa
7              5.0             3.4              1.5             0.2  setosa
8              4.4             2.9              1.4             0.2  setosa
9              4.9             3.1              1.5             0.1  setosa

In [40]:
#3.3.2 задание

data['sepal_length_cm'] = (data['sepal_length_cm'] - data['sepal_length_cm'].min()) / (data['sepal_length_cm'].max() - data['sepal_length_cm'].min())
data['sepal_width_cm'] = (data['sepal_width_cm'] - data['sepal_width_cm'].mean()) / data['sepal_width_cm'].std()
data.head(10)



sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.028611              1.4             0.2  setosa
1         0.166667       -0.124540              1.4             0.2  setosa
2         0.111111        0.336720              1.3             0.2  setosa
3         0.083333        0.106090              1.5             0.2  setosa
4         0.194444        1.259242              1.4             0.2  setosa
5         0.305556        1.951133              1.7             0.4  setosa
6         0.083333        0.797981              1.4             0.3  setosa
7         0.194444        0.797981              1.5             0.2  setosa
8         0.027778       -0.355171              1.4             0.2  setosa
9         0.166667        0.106090              1.5             0.1  setosa

-6.158037043254202e-16